const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Ground: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Hero_Shadow: 0},
	{direction: 0},
	{Pin: 0},
	{Flash: 0},
	{Hero: 0},
	{Keyboard: 0},
	{Ground2: 0},
	{Trigger_Break: 0},
	{ParticleBlock: 0},
	{BonusBox: 0},
	{BonusBoxTrigger: 0},
	{Fade: 0},
	{Coin: 0},
	{Direction: 0},
	{Enemy: 0},
	{EnemyBarrier: 0},
	{ScoreTxt: 0},
	{Bullet: 0},
	{Projectile: 0},
	{Hiddenlevel: 0},
	{TriggerBonusLevel: 0},
	{ExitHiddenLevel: 0},
	{NextLvl: 0},
	{NextLvl2: 0},
	{Score: 0},
	{BonusLevel: 0}
];

self.InstanceType = {
	Ground: class extends self.ISpriteInstance {},
	Hero_Shadow: class extends self.ISpriteInstance {},
	Hero: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ground2: class extends self.ISpriteInstance {},
	Trigger_Break: class extends self.ISpriteInstance {},
	ParticleBlock: class extends self.IParticlesInstance {},
	BonusBox: class extends self.ISpriteInstance {},
	BonusBoxTrigger: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyBarrier: class extends self.ISpriteInstance {},
	ScoreTxt: class extends self.ITextInstance {},
	Projectile: class extends self.ISpriteInstance {},
	Hiddenlevel: class extends self.ISpriteInstance {},
	TriggerBonusLevel: class extends self.ISpriteInstance {},
	ExitHiddenLevel: class extends self.ISpriteInstance {},
	NextLvl: class extends self.ISpriteInstance {},
	NextLvl2: class extends self.ISpriteInstance {}
}